# Generated by Django 5.0.2 on 2024-08-07 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_alter_transaction_rid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(editable=False)),
                ('status', models.CharField(choices=[('booked', 'Бронирование'), ('ticketed', 'Оплачено'), ('canceled', 'Отменено'), ('timeout', 'Истек срок оплаты')], default='booked', max_length=255, verbose_name='Статус')),
                ('client_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Почта клиента')),
                ('client_phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон клиента')),
                ('payer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя покупателя')),
                ('billing_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер брони')),
                ('amount', models.FloatField(verbose_name='Сумма для платежа')),
                ('paid', models.FloatField(blank=True, null=True, verbose_name='Всего оплачено')),
                ('book_class', models.CharField(choices=[('e', 'Эконом класс'), ('b', 'Бизнес класс'), ('f', 'Первый класс'), ('w', 'Комфорт')], max_length=250, verbose_name='Класс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_notification', models.BooleanField(default=False, editable=False)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявки на авиабилеты',
                'verbose_name_plural': 'Заявки на авиабилеты',
            },
        ),
        migrations.CreateModel(
            name='FlightCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_cancel', to='payment.transaction', verbose_name='Транзакция')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightrequest', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Отмена брони',
                'verbose_name_plural': 'Отмена брони',
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middlename', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('age', models.CharField(blank=True, choices=[('adt', 'Взрослый'), ('chd', 'Ребенок'), ('inf', 'Младенец без места'), ('src', 'Пенсионер'), ('yth', 'Подросток'), ('ins', 'Младенец с местом')], max_length=150, null=True, verbose_name='Тип возраста')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('doctype', models.CharField(blank=True, choices=[('C', 'Паспорт РФ'), ('B', 'Свидетельство о рождении РФ'), ('P', 'Заграничный паспорт РФ'), ('A', 'Иностранный документ'), ('M', 'Военный билет'), ('S', 'Паспорт моряка'), ('DP', 'Дипломатический паспорт'), ('WP', 'Служебный паспорт'), ('O', 'Удостоверение личности офицера'), ('L', 'Справка об утере паспорта'), ('R', 'Свидетельство на возвращение в РФ'), ('I', 'Не указан')], max_length=5, null=True, verbose_name='Тип документа')),
                ('docnum', models.CharField(blank=True, help_text='Серия и номер', max_length=50, null=True, verbose_name='Номер документа')),
                ('docexp', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('MI', 'Младенец мужского пола'), ('FI', 'Младенец женского пола')], max_length=5, null=True, verbose_name='Пол')),
                ('citizen', models.CharField(blank=True, help_text='код страны в формате ISO 3166-1 alpha-2', max_length=5, null=True, verbose_name='Код страны')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон номер пассажира')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Эл-поста пассажира')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='flights.flightrequest')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажир',
            },
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(help_text='Алматы', max_length=150, verbose_name='Откуда (город)')),
                ('from_iata', models.CharField(help_text='ALA', max_length=150, verbose_name='Код города')),
                ('from_country', models.CharField(help_text='Казахстан', max_length=150, verbose_name='Страна отправления')),
                ('to_name', models.CharField(help_text='Бишкек', max_length=150, verbose_name='Куда (город)')),
                ('to_iata', models.CharField(help_text='FRU', max_length=150, verbose_name='Код города')),
                ('to_country', models.CharField(help_text='Кыргызстан', max_length=150, verbose_name='Страна прибытие')),
                ('date_from', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата вылета')),
                ('date_to', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата прилета')),
                ('time_from', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время вылета')),
                ('time_to', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время прилета')),
                ('duration_hour', models.IntegerField(blank=True, help_text='В пути', null=True, verbose_name='Час')),
                ('duration_minute', models.IntegerField(blank=True, help_text='В пути', null=True, verbose_name='Минут')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='flights.flightrequest')),
            ],
            options={
                'verbose_name': 'Сегмент',
                'verbose_name_plural': 'Сегменты',
            },
        ),
    ]
