# Generated by Django 5.0.2 on 2024-09-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_aviaagreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviaagreement',
            options={'verbose_name': 'Политика соглашения об авиабилетах', 'verbose_name_plural': 'Политика соглашения об авиабилетах'},
        ),
    ]
