# Generated by Django 5.0.2 on 2024-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0006_alter_flightrequest_payler_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightrequest",
            name="transaction_id",
            field=models.CharField(editable=False, max_length=700, null=True),
        ),
    ]
