# Generated by Django 5.0.2 on 2024-11-23 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_flightrequest_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='partner_affiliate_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
