# Generated by Django 5.0.2 on 2024-11-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0009_alter_passengers_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightrequest",
            name="partner_affiliate_fee",
        ),
    ]
