# Generated by Django 5.0.2 on 2024-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0010_remove_flightrequest_partner_affiliate_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightrequest",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="flightrequest",
            name="is_baggage",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="flightrequest",
            name="provider",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="flightrequest",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
