# Generated by Django 5.0.2 on 2024-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_flightrequest_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='adt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='chd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='inf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
