# Generated by Django 5.0.2 on 2024-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_flightrequest_adt_flightrequest_chd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='partner_affiliate_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сборы'),
        ),
    ]
