# Generated by Django 5.0.2 on 2025-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0017_alter_airproviders_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightrequest",
            name="tid",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
