# Generated by Django 4.2.4 on 2023-10-27 12:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('seats', models.IntegerField(verbose_name='Доступно мест')),
                ('datefrom', models.DateField(verbose_name='Начало тура')),
                ('dateto', models.DateField(verbose_name='Окончание тура')),
                ('nights', models.IntegerField(verbose_name='Ночей')),
                ('days', models.IntegerField(verbose_name='Дней')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_pdf', models.FileField(upload_to='descriptions')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Питание', 'verbose_name_plural': 'Питание'},
        ),
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='День')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Тело')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tours.bustours')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программа',
            },
        ),
        migrations.CreateModel(
            name='TourExcursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Тело')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tours.bustours')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='TourCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Тело')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tours.bustours')),
            ],
            options={
                'verbose_name': 'Условие тура',
                'verbose_name_plural': 'Условие тура',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('body', models.TextField(verbose_name='Отзыв')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tours.bustours')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tours.bustours')),
            ],
            options={
                'verbose_name': 'Автобусный тур',
                'verbose_name_plural': 'Автобусные туры',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название города')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tours.bustours')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='bustours',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bus_tours.meals'),
        ),
    ]
