# Generated by Django 4.2.4 on 2023-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0002_bustours_alter_meals_options_tourprogram_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bustours",
            options={
                "verbose_name": "Автобусный тур",
                "verbose_name_plural": "Автобусные туры    ",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Галерея", "verbose_name_plural": "Галерея"},
        ),
        migrations.AlterField(
            model_name="bustours",
            name="description_pdf",
            field=models.FileField(
                upload_to="descriptions", verbose_name="Описание тура PDF"
            ),
        ),
    ]
