# Generated by Django 4.2.4 on 2023-10-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0003_alter_bustours_options_alter_gallery_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bustours",
            options={
                "verbose_name": "Автобусный тур",
                "verbose_name_plural": "Автобусные туры",
            },
        ),
        migrations.AlterField(
            model_name="bustours",
            name="description_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="descriptions",
                verbose_name="Описание тура PDF",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="bus_tours.bustours",
            ),
        ),
    ]
