# Generated by Django 4.2.4 on 2023-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0004_alter_bustours_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="img",
            field=models.ImageField(upload_to="gallery", verbose_name="Изображение"),
        ),
    ]
