# Generated by Django 4.2.4 on 2023-10-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tours', '0005_alter_gallery_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='bus_tours.bustours'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bus_tours.bustours'),
        ),
        migrations.AlterField(
            model_name='tourcondition',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='bus_tours.bustours'),
        ),
        migrations.AlterField(
            model_name='tourexcursions',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to='bus_tours.bustours'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='bus_tours.bustours'),
        ),
    ]
