# Generated by Django 4.2.4 on 2023-10-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tours', '0006_alter_cities_tour_alter_reviews_tour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='bustours',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bus_tours.meals', verbose_name='Питание'),
        ),
    ]
