# Generated by Django 4.2.4 on 2023-10-27 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tours', '0007_alter_gallery_options_alter_bustours_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата отзыва'),
            preserve_default=False,
        ),
    ]
