# Generated by Django 4.2.4 on 2023-10-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0009_bustours_departure_bustours_num_of_tourists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
    ]
