# Generated by Django 4.2.4 on 2023-10-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0011_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustours",
            name="cat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_tours.category",
                verbose_name="Категория",
            ),
        ),
    ]
