# Generated by Django 4.2.4 on 2023-10-31 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_tours', '0012_bustours_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Новая'), (2, 'ЧВ работе'), (3, 'Подтверждена')], default=1, verbose_name='Статус')),
                ('payment_status', models.IntegerField(choices=[(1, 'Не оплачена'), (2, 'Частично оплачена'), (3, 'Полностью оплачена')], default=1, verbose_name='Статус оплаты')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('gender', models.CharField(choices=[('Муж', 'Муж'), ('Жен', 'Жен')], max_length=3, verbose_name='Пол')),
                ('dateofborn', models.DateField(verbose_name='Дата рождения')),
                ('inn', models.CharField(max_length=100, verbose_name='ИНН')),
                ('passport_id', models.CharField(max_length=255, verbose_name='ID пасспорта')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(verbose_name='Орган выдачи')),
                ('validity', models.DateField(verbose_name='Срок действия')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('passport_front', models.ImageField(blank=True, null=True, upload_to='passports', verbose_name='Фото паспорта, передняя сторона')),
                ('passport_back', models.ImageField(blank=True, null=True, upload_to='passports', verbose_name='Фото паспорта, задняя сторона')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_tours.bustours')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Travelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofborn', models.DateField(verbose_name='Дата рождения')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('Муж', 'Муж'), ('Жен', 'Жен')], max_length=3, verbose_name='Пол')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bustour_travelers', to='bus_tours.bustourrequest')),
            ],
            options={
                'verbose_name': 'Путешественник',
                'verbose_name_plural': 'Путешественники',
            },
        ),
    ]
