# Generated by Django 4.2.4 on 2023-11-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tours', '0014_alter_bustourrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustourrequest',
            name='request_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер заявки'),
        ),
    ]
