# Generated by Django 4.2.4 on 2023-11-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0015_bustourrequest_request_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustours",
            name="country",
            field=models.CharField(default="", max_length=255, verbose_name="Страна"),
        ),
    ]
