# Generated by Django 5.0.2 on 2024-02-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0016_bustours_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bustours",
            options={
                "verbose_name": "Авторский тур",
                "verbose_name_plural": "Авторские туры",
            },
        ),
    ]
