# Generated by Django 5.0.2 on 2025-02-20 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0018_alter_bustourrequest_issued_by_alter_cities_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustours",
            name="available_dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Доступные даты",
            ),
        ),
    ]
