# Generated by Django 5.0.2 on 2025-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0019_bustours_available_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bustours",
            name="available_dates",
        ),
        migrations.AddField(
            model_name="bustours",
            name="currency",
            field=models.CharField(
                choices=[("KGZ", "KGZ"), ("USD", "USD"), ("EURO", "EURO")],
                default="Cом",
                max_length=50,
                verbose_name="Валюта",
            ),
        ),
    ]
