# Generated by Django 5.0.2 on 2025-02-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0020_remove_bustours_available_dates_bustours_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bustours",
            name="nights",
        ),
        migrations.AlterField(
            model_name="bustours",
            name="currency",
            field=models.CharField(
                choices=[("KGZ", "KGZ"), ("USD", "USD"), ("EURO", "EURO")],
                default="KGZ",
                max_length=50,
                verbose_name="Валюта",
            ),
        ),
    ]
