# Generated by Django 5.0.2 on 2025-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0021_remove_bustours_nights_alter_bustours_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustours",
            name="nights",
            field=models.IntegerField(default=2, verbose_name="Ночей"),
        ),
    ]
