# Generated by Django 5.0.2 on 2025-02-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0022_bustours_nights"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bustours",
            name="nights",
        ),
    ]
