# Generated by Django 5.0.2 on 2025-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_tours", "0023_remove_bustours_nights"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustours",
            name="records",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Количество записей"
            ),
        ),
    ]
