# Generated by Django 5.0.2 on 2024-02-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_remove_traveler_inn_traveler_passport_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveler",
            name="dateofborn",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
