# Generated by Django 5.0.2 on 2024-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_requesttour_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='passport_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия и номер з/п'),
        ),
    ]
