# Generated by Django 5.0.2 on 2024-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_requesthotel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesthotel",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Новая заявка"),
                    (2, "В процессе"),
                    (3, "Арендован"),
                    (4, "Отклонено"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
