# Generated by Django 5.0.2 on 2024-07-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_requesthotel_paid_alter_requesttour_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttour',
            name='from_main_view',
            field=models.BooleanField(default=True),
        ),
    ]
