# Generated by Django 5.0.2 on 2024-07-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_flight_date_begin_alter_flight_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttourservices',
            name='extended_fields',
        ),
        migrations.AlterField(
            model_name='requesttourservices',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='account.requesttour'),
        ),
    ]
