# Generated by Django 5.0.2 on 2024-07-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0031_remove_requesttourservices_flights_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tourist",
        ),
    ]
