# Generated by Django 5.0.2 on 2024-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0036_alter_manualrequests_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttour",
            name="payler_url",
            field=models.CharField(max_length=700, null=True),
        ),
    ]
