# Generated by Django 5.0.2 on 2024-09-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0043_manualrequests_request_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manualrequests",
            name="data",
        ),
    ]
