# Generated by Django 5.0.2 on 2024-11-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0047_traveler_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveler",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travelers",
                to="account.requesthotel",
            ),
        ),
    ]
