# Generated by Django 5.0.2 on 2024-12-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0052_alter_hoteltraveler_hotel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requesthotel",
            old_name="hotelid",
            new_name="hotelcode",
        ),
    ]
