# Generated by Django 5.0.2 on 2024-12-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_requesthotel_price_netto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthotel',
            name='price_netto',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (оригинальная)'),
        ),
    ]
