# Generated by Django 5.0.2 on 2025-02-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0058_alter_requesthotel_meal"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bonuses",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Bonuses"
            ),
        ),
    ]
