# Generated by Django 5.0.2 on 2024-04-06 12:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_alter_countries_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявки на авиабилеты",
                "verbose_name_plural": "Заявки на авиабилеты",
            },
        ),
        migrations.CreateModel(
            name="Segments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline", models.CharField(max_length=150, verbose_name="Авиалиния")),
                (
                    "from_name",
                    models.CharField(
                        help_text="Алматы",
                        max_length=150,
                        verbose_name="Откуда (город)",
                    ),
                ),
                (
                    "from_iata",
                    models.CharField(
                        help_text="ALA", max_length=150, verbose_name="Код города"
                    ),
                ),
                (
                    "from_country",
                    models.CharField(
                        help_text="Казахстан",
                        max_length=150,
                        verbose_name="Страна отправления",
                    ),
                ),
                (
                    "to_name",
                    models.CharField(
                        help_text="Бишкек", max_length=150, verbose_name="Куда (город)"
                    ),
                ),
                (
                    "to_iata",
                    models.CharField(
                        help_text="FRU", max_length=150, verbose_name="Код города"
                    ),
                ),
                (
                    "to_country",
                    models.CharField(
                        help_text="Кыргызстан",
                        max_length=150,
                        verbose_name="Страна прибытие",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время вылета"
                    ),
                ),
                (
                    "book_class",
                    models.CharField(
                        choices=[
                            ("e", "Эконом класс"),
                            ("b", "Бизнес класс"),
                            ("f", "Первый класс"),
                        ],
                        verbose_name="Класс",
                    ),
                ),
                (
                    "main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="search.flightrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сегмент",
                "verbose_name_plural": "Сегменты",
            },
        ),
    ]
