# Generated by Django 5.0.2 on 2024-04-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_passenger_token_alter_segments_book_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
