# Generated by Django 5.0.2 on 2024-04-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0009_delete_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="segments",
            name="main",
        ),
        migrations.DeleteModel(
            name="Passenger",
        ),
        migrations.DeleteModel(
            name="FlightRequest",
        ),
        migrations.DeleteModel(
            name="Segments",
        ),
    ]
