# Generated by Django 5.0.2 on 2024-04-18 09:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_remove_flightrequest_user_remove_segments_main_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('status', models.CharField(choices=[('0', 'Ожидает оплаты'), ('1', 'Подтверждено')], default='0', max_length=255, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявки на авиабилеты',
                'verbose_name_plural': 'Заявки на авиабилеты',
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middlename', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('age', models.CharField(blank=True, choices=[('adt', 'Взрослый'), ('chd', 'Ребенок'), ('inf', 'Младенец без места'), ('src', 'Пенсионер'), ('yth', 'Подросток'), ('ins', 'Младенец с местом')], max_length=150, null=True, verbose_name='Тип возраста')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('doctype', models.CharField(blank=True, choices=[('C', 'Паспорт РФ'), ('B', 'Свидетельство о рождении РФ'), ('P', 'Заграничный паспорт РФ'), ('A', 'Иностранный документ'), ('M', 'Военный билет'), ('S', 'Паспорт моряка'), ('DP', 'Дипломатический паспорт'), ('WP', 'Служебный паспорт'), ('O', 'Удостоверение личности офицера'), ('L', 'Справка об утере паспорта'), ('R', 'Свидетельство на возвращение в РФ'), ('I', 'Не указан')], max_length=5, null=True, verbose_name='Тип документа')),
                ('docnum', models.CharField(blank=True, help_text='Серия и номер', max_length=50, null=True, verbose_name='Номер документа')),
                ('docexp', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мучжина'), ('F', 'Женщина'), ('MI', 'Младенец мужского пола'), ('FI', 'Младенец женского пола')], max_length=5, null=True, verbose_name='Пол')),
                ('citizen', models.CharField(blank=True, help_text='код страны в формате ISO 3166-1 alpha-2', max_length=5, null=True, verbose_name='Код страны')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон номер пассажира')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Эл-поста пассажира')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='search.flightrequest')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажир',
            },
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=150, verbose_name='Авиалиния')),
                ('from_name', models.CharField(help_text='Алматы', max_length=150, verbose_name='Откуда (город)')),
                ('from_iata', models.CharField(help_text='ALA', max_length=150, verbose_name='Код города')),
                ('from_country', models.CharField(help_text='Казахстан', max_length=150, verbose_name='Страна отправления')),
                ('to_name', models.CharField(help_text='Бишкек', max_length=150, verbose_name='Куда (город)')),
                ('to_iata', models.CharField(help_text='FRU', max_length=150, verbose_name='Код города')),
                ('to_country', models.CharField(help_text='Кыргызстан', max_length=150, verbose_name='Страна прибытие')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время вылета')),
                ('book_class', models.CharField(choices=[('e', 'Эконом класс'), ('b', 'Бизнес класс'), ('f', 'Первый класс'), ('w', 'Комфорт')], max_length=250, verbose_name='Класс')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='search.flightrequest')),
            ],
            options={
                'verbose_name': 'Сегмент',
                'verbose_name_plural': 'Сегменты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('completed', 'Успешно завершено'), ('timeout', 'Превышено время платежа'), ('refund', 'Возврат')], max_length=255, verbose_name='Статус')),
                ('name', models.CharField(choices=[('tour', 'Тур'), ('hotel', 'Отель'), ('ticket', 'Авиа билет')], max_length=255, verbose_name='Платёж для')),
                ('request_id', models.UUIDField(blank=True, null=True, verbose_name='Айди запроса')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер отправителя')),
                ('amount', models.FloatField(verbose_name='Сумма платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежы',
            },
        ),
    ]
