# Generated by Django 5.0.2 on 2024-04-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0013_remove_segments_book_class_flightrequest_book_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="phone",
        ),
    ]
