# Generated by Django 5.0.2 on 2024-04-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_alter_flightrequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('MI', 'Младенец мужского пола'), ('FI', 'Младенец женского пола')], max_length=5, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='segments',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата и время вылета'),
        ),
    ]
