# Generated by Django 5.0.2 on 2024-04-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0016_alter_passengers_gender_alter_segments_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segments",
            name="airline",
        ),
    ]
