# Generated by Django 5.0.2 on 2024-04-19 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_alter_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='search.flightrequest'),
        ),
        migrations.AlterField(
            model_name='segments',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='search.flightrequest'),
        ),
    ]
