# Generated by Django 5.0.2 on 2024-04-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_alter_segments_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segments',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='segments',
            name='date_to',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата прилета'),
        ),
    ]
