# Generated by Django 5.0.2 on 2024-04-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_alter_transaction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
