# Generated by Django 5.0.2 on 2024-04-22 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_delete_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('rid', models.CharField(default='318282', editable=False, max_length=6, unique=True, verbose_name='Уникальный код')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('completed', 'Успешно завершено'), ('timeout', 'Превышено время платежа'), ('canceled', 'Отменен')], max_length=255, verbose_name='Статус')),
                ('name', models.CharField(choices=[('tour', 'Тур'), ('hotel', 'Отель'), ('ticket', 'Авиабилет')], max_length=255, verbose_name='Платёж для')),
                ('request_id', models.UUIDField(blank=True, null=True, verbose_name='Айди запроса')),
                ('amount', models.FloatField(verbose_name='Сумма для платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежы',
            },
        ),
    ]
