# Generated by Django 5.0.2 on 2024-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0036_transaction_tour_id_alter_flightcancel_flight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="tour_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Айди тура"),
        ),
    ]
