# Generated by Django 5.0.2 on 2024-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_alter_flightrequest_status_alter_flightrequest_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='paid',
            field=models.FloatField(blank=True, null=True, verbose_name='Всего оплачено'),
        ),
    ]
