# Generated by Django 5.0.2 on 2024-08-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0046_alter_flightcancel_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
