# Generated by Django 4.2.4 on 2023-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uon_id", models.IntegerField()),
                ("uon_subdomain", models.CharField(max_length=255)),
                ("datetime", models.DateTimeField()),
                ("type_id", models.IntegerField()),
                ("request_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Обращения CRM",
                "verbose_name_plural": "Обращения CRM",
            },
        ),
    ]
