# Generated by Django 4.2.4 on 2023-11-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createrequest",
            name="uon_id",
            field=models.IntegerField(default=46194),
        ),
    ]
