# Generated by Django 5.0.2 on 2024-07-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenfcm',
            options={'verbose_name': 'Токен', 'verbose_name_plural': 'Токены (Уведомление)'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Токен пользователя', 'verbose_name_plural': 'Токены пользователей (Уведомление)'},
        ),
    ]
