# Generated by Django 5.0.2 on 2024-07-18 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_usertoken_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Текст')),
                ('all_users', models.BooleanField(default=False, verbose_name='Выбрать всех пользователей')),
                ('selected_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Выбрать пользователей')),
            ],
            options={
                'verbose_name': 'Создать уведомление',
                'verbose_name_plural': 'Создать уведомление',
            },
        ),
    ]
