# Generated by Django 5.0.2 on 2024-07-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_customnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomNotification',
        ),
        migrations.DeleteModel(
            name='TokenFCM',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
