# Generated by Django 5.0.2 on 2024-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnotification',
            name='text',
            field=models.TextField(max_length=400, verbose_name='Текст'),
        ),
    ]
