# Generated by Django 4.2.4 on 2023-10-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stories",
            options={"verbose_name": "История", "verbose_name_plural": "Истории"},
        ),
        migrations.AddField(
            model_name="stories",
            name="views",
            field=models.IntegerField(default=1, verbose_name="Количество просмотров"),
        ),
        migrations.AlterField(
            model_name="stories",
            name="video",
            field=models.FileField(upload_to="stories", verbose_name="История"),
        ),
    ]
