# Generated by Django 4.2.4 on 2023-10-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_stories_options_stories_views_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stories",
            name="video",
        ),
        migrations.RemoveField(
            model_name="stories",
            name="views",
        ),
        migrations.AddField(
            model_name="stories",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.CreateModel(
            name="StoryVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.FileField(upload_to="stories", verbose_name="История")),
                (
                    "views",
                    models.IntegerField(
                        default=1, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.stories"
                    ),
                ),
            ],
            options={
                "verbose_name": "История",
                "verbose_name_plural": "Истории",
            },
        ),
    ]
