# Generated by Django 4.2.4 on 2023-10-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_stories_video_remove_stories_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyvideos',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.stories'),
        ),
    ]
