# Generated by Django 4.2.4 on 2023-10-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_storyvideos_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='story_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='storyvideos',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='main.stories'),
        ),
    ]
