# Generated by Django 4.2.4 on 2023-10-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_stories_img_alter_storyvideos_story"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stories",
            name="name",
        ),
    ]
